// <auto-generated />
using Lab9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab9.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229141914_ChangeToExternalImageLinks")]
    partial class ChangeToExternalImageLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab9.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("Lab9.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/42/305658/iphone-15-pro-blue-thumb-600x600.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 25000000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/42/307174/samsung-galaxy-s24-ultra-grey-thumb-600x600.jpg",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 30000000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/44/322631/apple-macbook-air-m3-13-inch-8gb-256gb-thumb-600x600.jpg",
                            Name = "MacBook Air M3",
                            Price = 27000000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/44/322442/asus-rog-strix-scar-18-g834jyr-i9-n4053w-thumb-600x600.jpg",
                            Name = "Laptop ASUS ROG Strix",
                            Price = 35000000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/54/289700/airpods-pro-2-thumb-600x600.jpg",
                            Name = "AirPods Pro Gen 2",
                            Price = 5900000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/2162/285077/marshall-emberton-ii-thumb-600x600.jpg",
                            Name = "Loa Marshall Emberton II",
                            Price = 4500000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/522/294101/ipad-pro-m2-11-wifi-xam-thumb-600x600.jpg",
                            Name = "iPad Pro M2",
                            Price = 21000000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/44/313333/dell-inspiron-15-3520-i5-71021696-thumb-600x600.jpg",
                            Name = "Laptop Dell Inspiron 15",
                            Price = 18000000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/7077/314227/apple-watch-s9-41mm-vien-nhom-day-cao-su-hong-thumb-600x600.jpg",
                            Name = "Apple Watch Series 9",
                            Price = 9500000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ImageUrl = "https://cdn.tgdd.vn/Products/Images/75/203498/chuột-gaming-logitech-g502-hero-1-600x600.jpg",
                            Name = "Chuột Logitech G502",
                            Price = 1200000m
                        });
                });

            modelBuilder.Entity("Lab9.Models.Product", b =>
                {
                    b.HasOne("Lab9.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lab9.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
